name: 'Dotnet Build and Test'
description: 'Build, test and collect code coverage for a .NET solution'

inputs:
  solution:
    description: 'Path to the solution file'
    required: true
  dotnet_version:
    description: '.NET SDK version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Restore dependencies
      shell: bash
      run: |
        dotnet restore ${{ inputs.solution }}

    - name: Build solution
      shell: bash
      run: |
        dotnet build ${{ inputs.solution }} --no-restore --configuration Release

    - name: Run tests with code coverage
      shell: bash
      run: |
        dotnet test ${{ inputs.solution }} \
          --no-build \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --verbosity normal
